version = 0.1
[default.deploy.parameters]
stack_name = "ec2-sg-state-change"
resolve_s3 = true
s3_prefix = "ec2-sg-state-change"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
